"""empty message

Revision ID: 313aad67267d
Revises: 
Create Date: 2021-03-20 19:25:18.147971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313aad67267d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=96), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('register', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('idx')
    )
    op.create_table('todo',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('register', sa.String(length=1000), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('member')
    # ### end Alembic commands ###
