"""empty message

Revision ID: e4c242d00e2a
Revises: 313aad67267d
Create Date: 2021-03-29 15:48:20.506240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4c242d00e2a'
down_revision = '313aad67267d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('secret', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'secret')
    # ### end Alembic commands ###
